server:
  port: 0

eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
    instanceId: ${spring.application.name}-${random.value}

spring:
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false