jwt:
  secret: ${JWT_SECRET}
  token:
    validity: ${JWT_TOKEN_VALIDITY}

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/flight_booking_system_auth?createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}