server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  token:
    validity: ${JWT_TOKEN_VALIDITY}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE